import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import * as core from './core.js';

const fromHex = h => Uint8Array.from(h.match(/../g), b => parseInt(b, 16));

test('fingerprints match what letsgo verify prints', () => {
  // Generated by letsgo's own randomart and pgpwords packages.
  const cases = JSON.parse(readFileSync(new URL('../../testdata/fingerprints.json', import.meta.url)));
  for (const c of cases) {
    const d = fromHex(c.sha256);
    assert.equal(core.randomart(d, core.randomartTitle(c.tag)), c.randomart, c.tag);
    assert.deepEqual(core.pgpWords(d), c.words, c.tag);
  }
});

test('tags parse in scope and order by semver', () => {
  assert.equal(core.parseTag('cli/v1.0.0'), null);
  assert.equal(core.parseTag('nightly'), null);
  assert.deepEqual(core.parseTag('cli/v1.2.3', 'cli/'), { major: 1, minor: 2, patch: 3, pre: [] });
  const tags = ['v1.0.0', 'v1.1.0-rc.10', 'v1.1.0-rc.2', 'v1.1.0', 'v0.9.0', 'v1.1.0-beta'];
  const sorted = tags.map(t => [t, core.parseTag(t)]).sort((a, b) => core.compareVersions(b[1], a[1])).map(x => x[0]);
  assert.deepEqual(sorted, ['v1.1.0', 'v1.1.0-rc.10', 'v1.1.0-rc.2', 'v1.1.0-beta', 'v1.0.0', 'v0.9.0']);
});

test('a retraction notice reads back', () => {
  const body = '> [!CAUTION]\n> **This release is retracted.** Corrupts state.\n>\n> `go get` will not select it, and `go list -m -retracted` explains why.\n> Use v1.0.1 or later.\n\nnotes';
  assert.deepEqual(core.readNotice(body), { reason: 'Corrupts state.', use: 'v1.0.1' });
  assert.equal(core.readNotice('### Features'), null);
});

test('specs name a repository or a module', () => {
  assert.deepEqual(core.parseSpec('o/r'), { owner: 'o', repo: 'r', prefix: '', id: 'o/r' });
  assert.deepEqual(core.parseSpec('o/r@cli'), { owner: 'o', repo: 'r', prefix: 'cli/', id: 'o/r@cli/' });
  assert.equal(core.parseSpec('o'), null);
  assert.equal(core.parseSpec('o/r/x'), null);
});

const rel = (tag, extra = {}) => ({ tag, version: core.parseTag(tag), prerelease: core.parseTag(tag).pre.length > 0, retracted: null, audit: null, manifest: null, ...extra });
const affected = { audits: [{ at: '2026-09-24T00:00:00Z', status: 'affected', findings: [{ id: 'GO-1', module: 'golang.org/x/net', fixed: 'v0.38.0' }] }] };
const clean = { audits: [{ at: '2026-10-07T00:00:00Z', status: 'clean' }] };
const mods = v => ({ builder: { go: 'go1.27.1' }, modules: { count: 1, list: [{ path: 'golang.org/x/net', version: v }] } });

test('the verdict points at the fix, skipping a retracted release', () => {
  const releases = [
    rel('v2.3.1', { manifest: mods('v0.38.0'), audit: clean }),
    rel('v2.3.0', { manifest: mods('v0.38.0'), retracted: { reason: 'Broken.' } }),
    rel('v2.2.0', { manifest: mods('v0.37.0'), audit: affected }),
    rel('v2.4.0-rc.1'),
  ];
  const v = core.verdict(releases, releases[2]);
  assert.equal(v.kind, 'danger');
  assert.equal(v.target.tag, 'v2.3.1');
  assert.equal(core.verdict(releases, releases[1]).title, 'v2.3.0 was retracted');
  assert.equal(core.verdict(releases, releases[0]).kind, 'success');
  assert.equal(core.latestStable(releases).tag, 'v2.3.1');
});

test('digests cover archives, executables, source and images', () => {
  const m = { artifacts: [{ name: 'a.tar.gz', os: 'linux', arch: 'amd64', size: 1, sha256: 'aa', binary: 'a', binary_sha256: 'bb' }],
    source: { archive: 's.tar.gz', sha256: 'cc' }, images: [{ reference: 'ghcr.io/o/a', digest: 'sha256:dd' }] };
  assert.deepEqual(core.digests(m).map(d => d.sha256), ['aa', 'bb', 'cc', 'dd']);
});

test('esc escapes markup', () => {
  assert.equal(core.esc(`<img src=x onerror="a('b')">`), '&lt;img src=x onerror=&quot;a(&#39;b&#39;)&quot;&gt;');
});
